import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ReactQueryProvider } from "@/react-query";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <nav>
            <ul>
              <li>
                <Link href="/rsc">React Server Component</Link>
              </li>
              <li>
                <Link href="/rh">Route Handler</Link>
              </li>
              <li>
                <Link href="/sa">Server Action</Link>
              </li>
            </ul>
          </nav>

          <main>{children}</main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
